### ISSUE TITLE
Link to cpp files in subfolders

### ISSUE THREAD

**Issue by roobre** [sudar/Arduino-Makefile#251]
It looks like `cpp` files in subfolders are ignored.

Would be possible to get these compiled and linked too? Subfoldering really helps when having lots of files :\

Regards.

**Comment by ladislas** [comment]
@roobre any news on the issue?

**Comment by sudar** [comment]
@roobre I am closing this ticket now because of inactivity.

Feel free to re-open if needed.

**Comment by martin-mh** [comment]
Hi everyone !
Same problem here.
I'm working on a medium sized arduino project. Here the explaination : the project use a LCD. To write on it, i've cut different states in something called "Menu". Each Menu is a class who define the behavior of each menus. Since a Menu is not the "core logic" of the app, i putted them into separated folder.
Headers files are compiled because i call them but it tell me an compilation error due to reference error on functions who are defined in .cpp.
And more I can't include cpp files from the header because i'm using forwarded class declarations.

Take a look here : https://github.com/martin-mh/Projet-SI-2015-2016/tree/a485d052c70d383b2369b381afd3dc0267d2156e

So i got to move everything in the root folder ! Here : https://github.com/martin-mh/Projet-SI-2015-2016

Do you have any work around or any fix for that ? Because having every files in the root folder is ugly, in my mind.
Thanks.

**Comment by sej7278** [comment]
given that arduino-builder has just implemented recursively search subdirectories and totally broken itself (as it tries to link to the existing precompiled temp files!) i don't think its a good idea

**Comment by martin-mh** [comment]
ah darn ! That's not a big deal in anyway, don't worry :p

**Comment by Overdrivr** [comment]
Any updates on that ? I would like as well to put source/headers files inside subfolders to organize code inside the library.

**Comment by Pharap** [comment]
This is still an issue.

Having classes (note: `class`es, not libraries) split into `.h` and `.cpp` files might not be 'idiomatic Arduino', but it is completely expected idiomatic C++.

By not handling such cases, the IDE is crippling the experienced programmers who are using well-established good coding practices.

**Comment by roobre** [comment]
For anyone still wondering how to do this, I just uglily script it inside my makefile:

```makefile
# This variable is local, name it however you want
SOURCE_FOLDERS = src src/Player src/Weapon

# These two are used by Arduino.mk
LOCAL_C_SRCS = $(foreach dir,$(SOURCE_FOLDERS),$(wildcard $(dir)/*.c))
LOCAL_CPP_SRCS = $(foreach dir,$(SOURCE_FOLDERS),$(wildcard $(dir)/*.cpp))
```

Hacky, but Just Works.
