### ISSUE TITLE
Reset of Leonardo boards

### ISSUE THREAD

**Issue by joh** [sudar/Arduino-Makefile#30]
Reset of Leonardo type boards is done a [bit differently](http://arduino.cc/en/Main/arduinoBoardLeonardo):

> Rather than requiring a physical press of the reset button before an upload, the Leonardo is designed in a way that allows it to be reset by software running on a connected computer. The reset is triggered when the Leonardo's virtual (CDC) serial / COM port is opened at 1200 baud and then closed. When this happens, the processor will reset, breaking the USB connection to the computer (meaning that the virtual serial / COM port will disappear). After the processor resets, the bootloader starts, remaining active for about 8 seconds.

Please consider adding support for this to **ard-reset-arduino**. I'm no Perl wiz, but the following Python code did the trick:

```
import serial

ser = serial.Serial("/dev/ttyACM0", 1200)
ser.open()
ser.close()
```

Cheers!

**Comment by alejolp** [comment]
Arduino Leonardo bootloader requires DTR to 0 to fully reset into the bootloader. This is what the [Arduino IDE is doing to reset a Leonardo](https://github.com/arduino/Arduino/blob/8385aedc642d6cd76b50ac5167307121007e5045/arduino-core/src/processing/app/Serial.java#L78):

```
    SerialPort serialPort = new SerialPort(iname);
    try {
      serialPort.openPort();
      serialPort.setParams(1200, 8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
      serialPort.setDTR(false);
      serialPort.closePort();
      return true;
    }
```

My Python script to reset a Leonardo is like this:

```
import serial
import sys
ser = serial.Serial()
ser.port = sys.argv[1]
ser.baudrate = 1200
ser.open()
ser.setDTR(0)
ser.close()
```

ALSO: sleep for 1 second before calling the programmer (avrdude, etc); give time to the bootloader to start.

**Comment by CMCDragonkai** [comment]
If I have a Python script running it at 9600 baud.
Should the reset script be running at the closing of the python script, or the startup of the python script? Since my serial port is already open, do I need to close it, then open it, set it to 1200 baud then close it? Or can I just set it to 1200 then close it?

**Comment by alejolp** [comment]
@CMCDragonkai How are you calling the Python script? Are you sleeping for 1 second after closing the serial port and before trying to talk to the bootloader?

**Comment by CMCDragonkai** [comment]
@alejolp I don't quite understand your question. Are you saying to close the serial port, sleep for 1 second, then reopen? How does this reset the Leonardo (Leostick)? My serial ports are already being closed when I shutdown the Python program.

This answer says http://stackoverflow.com/a/21082531/582917 that you just need to toggle the DTR. What's the relationship between opening and closing the serial port,  the DTR toggle and the 1200 baud? Why is all this required to just reset the board?

**Comment by alejolp** [comment]
@CMCDragonkai The reset procedure is: open port at 1200 bps with DTR=false, and close. You need to wait 1 second to reset and the bootloader to kick in. Then you can talk to the bootloader and upload the firmware or whatever. If you have the serial port already open somewhere else, you need to close it first, otherwise you don't. [Check out the context on Arduino IDE touching the port for reset](https://github.com/arduino/Arduino/blob/ec2e9a642a085b32701cf81297ee7c1570177195/arduino-core/src/cc/arduino/packages/uploaders/SerialUploader.java#L144).
