### ISSUE TITLE
Confusing and misdocumented need to specify "mega.menu.cpu.atmega256"

### ISSUE THREAD

**Issue by RobertLRead** [sudar/Arduino-Makefile#414]

**Comment by sej7278** [comment]
take it up with arduino, they came up with the submenu system, otherwise here's our docs: 

https://github.com/sudar/Arduino-Makefile/blob/master/arduino-mk-vars.md#board_sub

of course its not required in arduino 1.0, so that's another solution, especially if you're only using a mega2560, ide 1.6 is pretty pointless for that board
