### ISSUE TITLE
ELF link uses $(CC), not $(CXX)

### ISSUE THREAD

**Issue by kpfleming** [sudar/Arduino-Makefile#644]
I've just started using this Makefile kit (it's quite nice) for a SAMD-based small project: the project currently contains one .ino file and some .hpp files (which are '#include'-d into the .ino file for the moment).

I got everything to compile, but the final link to produce the ELF file failed with a number of missing symbols, all of which come from the C++ standard library. While looking at Arduino.mk [here](https://github.com/sudar/Arduino-Makefile/blob/c7eb909b849e354fdb7630d11405ea6de706f1ba/Arduino.mk#L1679) I noticed that the linking is being done by calling $(CC) instead of $(CXX), which means the C++ standard library doesn't get included into the link automatically.

While I've made this change in my local Arduino.mk and now the project links successfully, I can't help but think that this is something which shouldn't be necessary, as pretty much all Arduino projects (at least those which originated in the IDE) are in C++ and require the standard library. Is there some sort of configuration setting I've missed?

**Comment by tuna-f1sh** [comment]
Yes looks like you are right. The Arduino IDE also calls `g++` for linking this is an oversight in the current SAM support. I think it hasn't been picked up prior to this since I've not used the C++ standard library with Arduino and most libraries don't. 

Suggest you make a pull request with this minor change. Thanks.

**Comment by sej7278** [comment]
merged thanks
